import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit

import pytest

from eigrel.backends import Requirement
from eigrel.backends.spark import JDBC_DRIVERS, JDBC_HELPER, generate, runtime_requirements
from eigrel.compiler import compile_source


def spark_code(source: str) -> str:
    return generate(compile_source(source), 'test.eig')


def test_header_and_session() -> None:
    code = spark_code('dataset d from csv("d.csv")')
    assert code.startswith('"""Generated by eigrel ')
    assert 'from test.eig for Apache Spark. Do not edit."""' in code
    assert "spark = SparkSession.builder.appName('eigrel: test.eig').getOrCreate()" in code
    assert "os.environ.setdefault('PYSPARK_PYTHON', sys.executable)" in code
    assert 'spark.jars.packages' not in code
    assert code.endswith('spark.stop()\n')


def test_file_sources() -> None:
    code = spark_code(
        'dataset a from csv("a.csv")\ndataset b from parquet("b.parquet")\n'
        'dataset c from json("c.jsonl")\ndataset e from json("e.json")'
    )
    assert "a = spark.read.csv('a.csv', header=True, inferSchema=True)" in code
    assert "b = spark.read.parquet('b.parquet')" in code
    assert "c = spark.read.json('c.jsonl')" in code
    assert "e = spark.read.option('multiLine', True).json('e.json')" in code


def test_sql_and_bigquery_sources_configure_packages() -> None:
    code = spark_code(
        'dataset a from sql("sqlite:///shop.db", "orders")\n'
        'dataset b from sql(env("DB_URL"), "shop.users")\n'
        'dataset c from bigquery("my-project.s.t")'
    )
    assert "a_jdbc, a_package = jdbc_options('sqlite:///shop.db', 'orders')" in code
    assert "b_jdbc, b_package = jdbc_options(os.environ['DB_URL'], 'shop.users')" in code
    assert "packages = sorted({a_package, b_package, 'com.google.cloud.spark:" in code
    assert ".config('spark.jars.packages', ','.join(packages)).getOrCreate()" in code
    assert "a = spark.read.format('jdbc').options(**a_jdbc).load()" in code
    assert "c = spark.read.format('bigquery').load('my-project.s.t')" in code
    assert 'def jdbc_options(url, table):' in code
    assert 'from urllib.parse import unquote, urlsplit' in code


def test_filters_and_select() -> None:
    code = spark_code(
        'dataset d from csv("d.csv")\n'
        'transform d { filter not (a > -1) or b == "x" and c != true\n select a, b }'
    )
    assert (
        "d = d.filter((~((F.col('a') > -(F.lit(1)))) | ((F.col('b') == F.lit('x'))"
        " & (F.col('c') != F.lit(True)))))"
    ) in code
    assert "d = d.select('a', 'b')" in code


@pytest.mark.parametrize(
    ('model', 'expected'),
    [
        (
            'random_forest { trees = 10, max_depth = 4, min_samples_leaf = 2 }',
            (
                "RandomForestClassifier(featuresCol='__eigrel_features', labelCol='__eigrel_label',"
                ' numTrees=10, maxDepth=4, minInstancesPerNode=2, seed=42)'
            ),
        ),
        (
            'gradient_boosting { trees = 30, learning_rate = 0.1 }',
            (
                "GBTClassifier(featuresCol='__eigrel_features', labelCol='__eigrel_label',"
                ' maxIter=30, stepSize=0.1, seed=42)'
            ),
        ),
        (
            'logistic_regression { max_iter = 50, c = 4 }',
            (
                "LogisticRegression(featuresCol='__eigrel_features', labelCol='__eigrel_label',"
                ' maxIter=50, regParam=0.25)'
            ),
        ),
        (
            'decision_tree { task = regression }',
            (
                "DecisionTreeRegressor(featuresCol='__eigrel_features', labelCol='__eigrel_label',"
                ' seed=42)'
            ),
        ),
        (
            'linear_regression',
            "LinearRegression(featuresCol='__eigrel_features', labelCol='__eigrel_label')",
        ),
    ],
)
def test_algorithms_map_to_mllib(model: str, expected: str) -> None:
    code = spark_code(f'dataset d from csv("d.csv")\nmodel m = {model}\ntrain m {{ target = y }}')
    assert expected in code


def test_training_and_evaluation_code() -> None:
    code = spark_code(
        'dataset d from csv("d.csv")\nfeatures d { a, b }\n'
        'model m = random_forest\ntrain m { target = y, validation = 0.25, seed = 7 }\n'
        'evaluate m { metrics = [accuracy, precision, auc] }\n'
        'dataset e from csv("e.csv")\nmodel n = random_forest\ntrain n { data = e, target = y }\n'
        'model r = linear_regression\ntrain r { data = d, target = z }\n'
        'evaluate r { metrics = [mae, r2] }'
    )
    assert "m_features = ['a', 'b']" in code
    assert "r_features = ['a', 'b']" in code
    assert "n_features = [c for c in e.columns if c not in ('y',)]" in code
    assert 'm_train, m_test = m_data.randomSplit([0.75, 0.25], seed=7)' in code
    assert "m_evaluator.setMetricName('accuracy')" in code
    assert (
        "m_evaluator.setMetricName('precisionByLabel' if m_binary else 'weightedPrecision')" in code
    )
    assert 'if m_binary:' in code and 'n/a (Spark computes AUC for 0/1 targets only)' in code
    assert "r_data = d.withColumn('__eigrel_label', F.col('z').cast('double'))" in code
    assert "r_evaluator.setMetricName('mae')" in code
    compile(code, 'generated.py', 'exec')  # valid Python


def test_names_avoid_spark_helpers() -> None:
    code = spark_code(
        'dataset spark from csv("d.csv")\nmodel m = random_forest\n'
        'dataset m_pred from csv("e.csv")\ntrain m { data = spark, target = y }'
    )
    assert "spark_ = spark.read.csv('d.csv'" in code
    assert 'm_ = Pipeline(' in code


def test_runtime_requirements() -> None:
    assert runtime_requirements(compile_source('dataset d from csv("d.csv")')) == [
        Requirement('pyspark', 'spark')
    ]


def jdbc(url: str, table: str = 't') -> tuple[dict[str, str], str]:
    namespace: dict[str, object] = {
        'JDBC_DRIVERS': JDBC_DRIVERS,
        'urlsplit': urlsplit,
        'unquote': unquote,
    }
    exec(JDBC_HELPER, namespace)  # noqa: S102 - the helper ships inside generated scripts
    return namespace['jdbc_options'](url, table)  # type: ignore[operator, no-any-return]


def test_jdbc_options_from_sqlalchemy_urls() -> None:
    options, package = jdbc('postgresql+psycopg://ana:p%40ss@db.example.com:5433/shop', 's.t')
    assert options == {
        'url': 'jdbc:postgresql://db.example.com:5433/shop',
        'dbtable': 's.t',
        'driver': 'org.postgresql.Driver',
        'user': 'ana',
        'password': 'p@ss',
    }
    assert package.startswith('org.postgresql:postgresql:')
    assert jdbc('mysql://h/db')[0]['url'] == 'jdbc:mysql://h/db'
    assert jdbc('mariadb+pymysql://h:3307/db')[0]['url'] == 'jdbc:mariadb://h:3307/db'
    assert jdbc('sqlite:///data/shop.db')[0]['url'] == 'jdbc:sqlite:data/shop.db'
    assert jdbc('sqlite:////abs/shop.db')[0]['url'] == 'jdbc:sqlite:/abs/shop.db'
    with pytest.raises(SystemExit, match='Spark cannot read oracle databases yet'):
        jdbc('oracle://h/db')


def run_on_spark(program: Path) -> str:
    code = generate(compile_source(program.read_text()), program.name)
    result = subprocess.run(
        [sys.executable, '-c', code],
        cwd=program.parent,
        capture_output=True,
        text=True,
        check=True,
        env={**os.environ, 'PYSPARK_PYTHON': sys.executable},
        timeout=600,
    )
    return result.stdout


@pytest.mark.spark
def test_classification_runs_on_spark(examples_dir: Path) -> None:
    out = run_on_spark(examples_dir / 'ml.eig')
    assert re.search(r'churn: random_forest classification, trained on \d+ rows', out)
    assert re.search(r'  f1         0\.\d{4}', out)


@pytest.mark.spark
def test_regression_runs_on_spark(examples_dir: Path) -> None:
    out = run_on_spark(examples_dir / 'regression.eig')
    assert 'income_model: gradient_boosting regression' in out
    assert re.search(r'  r2    0\.\d{4}', out)


@pytest.mark.spark
def test_sqlite_through_jdbc_and_text_columns(tmp_path: Path, examples_dir: Path) -> None:
    import shutil

    shutil.copy(examples_dir / 'data' / 'customers.db', tmp_path / 'customers.db')
    (tmp_path / 'colors.jsonl').write_text(
        ''.join(
            f'{{"x": {i}, "color": "{["red", "blue", "green"][i % 3]}", "label": "{"yes" if i % 3 else "no"}"}}\n'
            for i in range(60)
        )
    )
    program = tmp_path / 'p.eig'
    program.write_text(
        'dataset c from sql("sqlite:///customers.db", "customers")\n'
        'transform c { filter age >= 18\n select age, income, purchases, churned }\n'
        'model churn = logistic_regression { c = 10 }\n'
        'train churn { data = c, target = churned }\n'
        'evaluate churn { metrics = [accuracy, auc] }\n'
        'dataset colors from json("colors.jsonl")\n'
        'model kind = decision_tree\n'
        'train kind { data = colors, target = label }\n'
        'evaluate kind { metrics = [accuracy, f1, auc] }\n'
    )
    out = run_on_spark(program)
    assert 'churn: logistic_regression classification' in out
    assert re.search(r'  auc       0\.\d{4}', out)
    assert 'kind: decision_tree classification' in out
    assert '  auc       n/a (Spark computes AUC for 0/1 targets only)' in out


def test_cleaning_xgboost_and_register_code() -> None:
    code = spark_code(
        'dataset d from csv("d.csv")\n'
        'transform d { fill city = "x", n = 0\n drop_missing a\n drop_missing }\n'
        'model m = xgboost { trees = 30, max_depth = 3, learning_rate = 0.1 }\n'
        'train m { target = y }\nevaluate m { metrics = [f1] }\n'
        'register m { name = "churn", experiment = "e" }\n'
        'model r = linear_regression\ntrain r { target = n }\nregister r\n'
    )
    assert "d = d.fillna({'city': 'x', 'n': 0})" in code
    assert "d = d.dropna(subset=['a'])" in code
    assert 'd = d.dropna()' in code
    assert (
        "SparkXGBClassifier(features_col='__eigrel_features', label_col='__eigrel_label',"
        ' n_estimators=30, max_depth=3, learning_rate=0.1, random_state=42, verbose=False,'
        ' verbosity=0)'
    ) in code
    assert "logging.getLogger('XGBoost-PySpark').setLevel(logging.WARNING)" in code
    assert "m_labels = StringIndexer(inputCol='y', outputCol='__eigrel_label')" in code
    assert "mlflow.set_experiment('e')" in code
    assert "mlflow.spark.log_model(\n        m, 'model', registered_model_name='churn'" in code
    assert code.count('mlflow.log_metrics(') == 1  # r has no evaluation
    assert 'print("r: registered in MLflow as \'r\', version"' in code
    compile(code, 'generated.py', 'exec')


def test_spark_requirements_for_xgboost_and_mlflow() -> None:
    graph = compile_source(
        'dataset d from csv("d.csv")\nmodel m = xgboost\ntrain m { target = y }\nregister m'
    )
    assert [r.module for r in runtime_requirements(graph)] == ['pyspark', 'xgboost', 'mlflow']


@pytest.mark.spark
def test_cleaning_xgboost_and_register_run_on_spark(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import mlflow
    import pandas as pd

    rows = ['x,city,plan']
    for i in range(120):
        x = '' if i % 17 == 0 else str(i % 30)
        city = '' if i % 11 == 0 else ['rio', 'sp'][i % 2]
        rows.append(f'{x},{city},{["basic", "pro"][(i % 30) // 15]}')
    (tmp_path / 'plans.csv').write_text('\n'.join(rows) + '\n')
    tracking = f'sqlite:///{tmp_path / "mlflow.db"}'
    monkeypatch.setenv('MLFLOW_TRACKING_URI', tracking)
    program = tmp_path / 'plans.eig'
    program.write_text(
        'dataset d from csv("plans.csv")\n'
        'transform d { fill city = "unknown"\n drop_missing x }\n'
        'model m = xgboost { trees = 10, max_depth = 2 }\n'
        'train m { target = plan }\n'
        'evaluate m { metrics = [accuracy] }\n'
        'register m { name = "spark-plans" }\n'
    )
    script = tmp_path / 'plans_spark.py'
    script.write_text(generate(compile_source(program.read_text()), program.name))
    result = subprocess.run(
        [sys.executable, str(script)],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        check=True,
        env={**os.environ, 'PYSPARK_PYTHON': sys.executable},
        timeout=900,
    )
    assert 'm: xgboost classification' in result.stdout
    assert "m: registered in MLflow as 'spark-plans', version 1" in result.stdout

    mlflow.set_tracking_uri(tracking)
    version = mlflow.MlflowClient().get_model_version('spark-plans', '1')
    assert mlflow.get_run(version.run_id).data.params['algorithm'] == 'xgboost'
    assert pd.notna(version.run_id)
