import sqlite3
from contextlib import closing
from pathlib import Path

import duckdb
import pandas as pd
import pytest

from eigrel.backends.sql import dataset_queries, dialect_for, generate, render, select_all
from eigrel.compiler import compile_source, ir


def query(source: str, dataset: str = 'd') -> str:
    graph = compile_source(source)
    return render(next(q for q in dataset_queries(graph) if q.dataset == dataset))


@pytest.mark.parametrize(
    ('source', 'dialect'),
    [
        ('csv("d.csv")', 'duckdb'),
        ('parquet("d.parquet")', 'duckdb'),
        ('json("d.json")', 'duckdb'),
        ('bigquery("my-project.s.t")', 'bigquery'),
        ('sql("postgresql+psycopg://u@h/db", "t")', 'postgresql'),
        ('sql("postgres://u@h/db", "t")', 'postgresql'),
        ('sql("mysql+pymysql://u@h/db", "t")', 'mysql'),
        ('sql("mariadb://u@h/db", "t")', 'mysql'),
        ('sql("sqlite:///shop.db", "t")', 'sqlite'),
        ('sql("oracle://u@h/db", "t")', 'ansi'),
        ('sql(env("DB_URL"), "t")', 'ansi'),
    ],
)
def test_dialect_follows_the_source(source: str, dialect: str) -> None:
    load = compile_source(f'dataset d from {source}').ops[0]
    assert isinstance(load, ir.Load)
    assert dialect_for(load).name == dialect


def test_sources_and_quoting() -> None:
    assert query('dataset d from csv("it\'s.csv")') == "SELECT * FROM read_csv_auto('it''s.csv')"
    assert query('dataset d from parquet("d.parquet")') == "SELECT * FROM read_parquet('d.parquet')"
    assert query('dataset d from json("d.json")') == "SELECT * FROM read_json_auto('d.json')"
    assert (
        query('dataset d from sql("sqlite://", "shop.orders")') == 'SELECT * FROM "shop"."orders"'
    )
    assert query('dataset d from sql("mysql://h/db", "orders")') == 'SELECT * FROM `orders`'
    assert query('dataset d from bigquery("my-project.s.t")') == 'SELECT * FROM `my-project.s.t`'


def test_filters_and_projection_merge_into_one_select() -> None:
    sql = query(
        'dataset d from sql("sqlite://", "t")\n'
        'transform d { filter a > 1 and c == true\n select a, b, c }\n'
        'transform d { select a, b\n filter not (b == "x\'y") or a % 2 != 0 }\n'
        'transform d { filter -a < 1.5 }'
    )
    assert sql == (
        'SELECT "a", "b" FROM "t" WHERE (("a" > 1) AND ("c" = TRUE))'
        ' AND ((NOT ("b" = \'x\'\'y\')) OR (("a" % 2) <> 0))'
        ' AND ((-"a") < 1.5)'
    )


def test_bigquery_uses_mod_and_backticks() -> None:
    sql = query('dataset d from bigquery("my-project.s.t")\ntransform d { filter a % 3 == 0 }')
    assert sql == 'SELECT * FROM `my-project.s.t` WHERE (MOD(`a`, 3) = 0)'


def test_select_all_ignores_transforms() -> None:
    graph = compile_source('dataset d from sql("sqlite://", "t")\ntransform d { select a }')
    load = graph.ops[0]
    assert isinstance(load, ir.Load)
    assert select_all(load) == 'SELECT * FROM "t"'


def test_generate_lists_every_dataset_and_skips_models() -> None:
    code = generate(
        compile_source(
            'dataset a from csv("a.csv")\n'
            'dataset b from sql("sqlite://", "b")\n'
            'transform a { select x, y }\n'
            'model m = random_forest\ntrain m { data = a, target = y }\n'
        ),
        'p.eig',
    )
    assert code.splitlines() == [
        f'-- Generated by eigrel {__import__("eigrel").__version__} from p.eig. Do not edit.',
        '',
        '-- dataset a (csv, duckdb dialect)',
        'SELECT "x", "y" FROM read_csv_auto(\'a.csv\');',
        '',
        '-- dataset b (sql, sqlite dialect)',
        'SELECT * FROM "b";',
        '',
        '-- Models are not compiled to SQL: m',
    ]


@pytest.fixture
def frame() -> pd.DataFrame:
    return pd.DataFrame(
        {'age': [15, 20, 30, 40], 'city': ['a', 'b', "c'd", 'b'], 'vip': [1, 0, 1, 1]}
    )


PIPELINE = 'transform d {{ filter age >= 18 and city != "a"\n select age, city }}'


@pytest.mark.parametrize(
    ('fmt', 'write'),
    [
        ('csv', lambda f, p: f.to_csv(p, index=False)),
        ('parquet', lambda f, p: f.to_parquet(p)),
        ('json', lambda f, p: f.to_json(p, orient='records')),
    ],
)
def test_generated_sql_runs_on_duckdb(
    frame: pd.DataFrame, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, fmt: str, write: object
) -> None:
    write(frame, tmp_path / f'data.{fmt}')  # type: ignore[operator]
    monkeypatch.chdir(tmp_path)
    sql = query(f'dataset d from {fmt}("data.{fmt}")\n' + PIPELINE.format())
    rows = duckdb.sql(sql).fetchall()
    assert sorted(rows) == [(20, 'b'), (30, "c'd"), (40, 'b')]


def test_generated_sql_runs_on_sqlite(frame: pd.DataFrame, tmp_path: Path) -> None:
    database = tmp_path / 'shop.db'
    with closing(sqlite3.connect(database)) as connection:
        frame.to_sql('people', connection, index=False)
        sql = query('dataset d from sql("sqlite:///shop.db", "people")\n' + PIPELINE.format())
        rows = connection.execute(sql).fetchall()
    assert sorted(rows) == [(20, 'b'), (30, "c'd"), (40, 'b')]


def test_fill_and_drop_missing_become_coalesce_and_is_not_null() -> None:
    sql = query(
        'dataset d from sql("sqlite://", "t")\n'
        'transform d { fill a = 0, b = "x"\n filter a > 1\n select a, b, c\n drop_missing }'
    )
    assert sql == (
        'SELECT COALESCE("a", 0) AS "a", COALESCE("b", \'x\') AS "b", "c" FROM "t"'
        ' WHERE (COALESCE("a", 0) > 1) AND (COALESCE("a", 0) IS NOT NULL)'
        ' AND (COALESCE("b", \'x\') IS NOT NULL) AND ("c" IS NOT NULL)'
    )
    assert query(
        'dataset d from bigquery("my-project.s.t")\ntransform d { fill a = 1\n fill a = 2 }'
    ) == ('SELECT * REPLACE (COALESCE(COALESCE(`a`, 1), 2) AS `a`) FROM `my-project.s.t`')
    assert query(
        'dataset d from sql("sqlite://", "t")\ntransform d { fill c = false\n select c }'
    ) == ('SELECT COALESCE("c", FALSE) AS "c" FROM "t"')


@pytest.mark.parametrize(
    ('transform', 'message'),
    [
        ('drop_missing', "SQL needs the column names for drop_missing in 'd'"),
        ('fill a = 0', "sqlite SQL cannot fill columns of 'd' without knowing all of them"),
    ],
)
def test_unsupported_cleaning(transform: str, message: str) -> None:
    from eigrel.backends import UnsupportedError

    with pytest.raises(UnsupportedError, match=message):
        query(f'dataset d from sql("sqlite://", "t")\ntransform d {{ {transform} }}')


def test_cleaning_sql_runs_on_duckdb(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    (tmp_path / 'data.csv').write_text('age,city\n15,a\n,b\n30,\n40,c\n')
    monkeypatch.chdir(tmp_path)
    sql = query(
        'dataset d from csv("data.csv")\n'
        'transform d { fill city = "unknown"\n drop_missing age\n filter city != "a" }'
    )
    assert sorted(duckdb.sql(sql).fetchall()) == [(30, 'unknown'), (40, 'c')]
