"""Python backend: turn the IR into a readable pandas + scikit-learn script."""

import keyword
from dataclasses import dataclass, field

from eigrel import __version__
from eigrel.backends import sql
from eigrel.compiler import ast, ir


@dataclass(frozen=True)
class Requirement:
    """A module the generated code imports, and the eigrel extra that installs it."""

    module: str
    extra: str


def runtime_requirements(graph: ir.Graph) -> list[Requirement]:
    """The modules a program needs at run time, depending on its sources and models."""
    formats = {op.format for op in graph.ops if isinstance(op, ir.Load)}
    requirements = [Requirement('pandas', 'python')]
    if any(isinstance(op, ir.Train) for op in graph.ops):
        requirements.append(Requirement('sklearn', 'python'))
    if 'parquet' in formats:
        requirements.append(Requirement('pyarrow', 'python'))
    if 'sql' in formats:
        requirements.append(Requirement('sqlalchemy', 'sql'))
    if 'bigquery' in formats:
        requirements.append(Requirement('google.cloud.bigquery', 'bigquery'))
        requirements.append(Requirement('db_dtypes', 'bigquery'))
    return requirements


# Eigrel algorithm -> (module, classifier class, regressor class, accepts random_state)
ESTIMATORS: dict[str, tuple[str, str | None, str | None, bool]] = {
    'random_forest': (
        'sklearn.ensemble',
        'RandomForestClassifier',
        'RandomForestRegressor',
        True,
    ),
    'decision_tree': ('sklearn.tree', 'DecisionTreeClassifier', 'DecisionTreeRegressor', True),
    'gradient_boosting': (
        'sklearn.ensemble',
        'GradientBoostingClassifier',
        'GradientBoostingRegressor',
        True,
    ),
    'logistic_regression': ('sklearn.linear_model', 'LogisticRegression', None, True),
    'linear_regression': ('sklearn.linear_model', None, 'LinearRegression', False),
}

# Eigrel parameter name -> scikit-learn keyword, where they differ.
PARAM_NAMES = {'trees': 'n_estimators', 'c': 'C'}

# Metric -> (scikit-learn function, uses the classification `average` argument)
METRIC_FUNCTIONS = {
    'accuracy': ('accuracy_score', False),
    'precision': ('precision_score', True),
    'recall': ('recall_score', True),
    'f1': ('f1_score', True),
    'auc': ('roc_auc_score', False),
    'mae': ('mean_absolute_error', False),
    'mse': ('mean_squared_error', False),
    'rmse': ('root_mean_squared_error', False),
    'r2': ('r2_score', False),
}

BINARY_OPERATORS = {'and': '&', 'or': '|'}

# Variables the generated code creates for each model, as suffixes of the model's name.
MODEL_HELPERS = (
    '_X',
    '_y',
    '_X_train',
    '_X_test',
    '_y_train',
    '_y_test',
    '_pred',
    '_average',
    '_proba',
    '_scores',
)

# Names the generated code imports or calls; Eigrel names must not shadow them.
RESERVED = {
    'pd',
    'os',
    'bigquery',
    'create_engine',
    'print',
    'len',
    'set',
    'train_test_split',
    *(function for function, _ in METRIC_FUNCTIONS.values()),
    *(cls for _, *classes, _ in ESTIMATORS.values() for cls in classes if cls is not None),
}


@dataclass
class _Generator:
    graph: ir.Graph
    imports: dict[str, set[str]] = field(default_factory=dict)
    modules: set[str] = field(default_factory=lambda: {'pandas as pd'})
    lines: list[str] = field(default_factory=list)
    # Python variable holding the value of each IR op.
    variables: dict[int, str] = field(default_factory=dict)
    # Eigrel name -> Python variable name.
    names: dict[str, str] = field(default_factory=dict)

    def generate(self, source_name: str) -> str:
        self._assign_names()
        for op in self.graph.ops:
            match op:
                case ir.Load():
                    self._load(op)
                case ir.Filter():
                    self._filter(op)
                case ir.Select():
                    self._select(op)
                case ir.Train():
                    self._train(op)
                case ir.Evaluate():
                    self._evaluate(op)
        header = [
            f'"""Generated by eigrel {__version__} from {source_name}. Do not edit."""',
            '',
            *(f'import {module}' for module in sorted(self.modules)),
        ]
        for module in sorted(self.imports):
            header.append(f'from {module} import {", ".join(sorted(self.imports[module]))}')
        return '\n'.join([*header, *self.lines]) + '\n'

    def _load(self, op: ir.Load) -> None:
        name = self._bind(op)
        self._section(f'Dataset {op.name}')
        location = op.args[0]
        match op.format:
            case 'csv':
                read = f'pd.read_csv({location!r})'
            case 'parquet':
                read = f'pd.read_parquet({location!r})'
            case 'json':
                lines = str(location).lower().endswith(('.jsonl', '.ndjson'))
                read = f'pd.read_json({location!r}{", lines=True" if lines else ""})'
            case 'sql':
                self._import('sqlalchemy', 'create_engine')
                engine = f'create_engine({self._source_value(location)})'
                read = f'pd.read_sql_query({sql.select_all(op)!r}, {engine})'
            case 'bigquery':
                self._import('google.cloud', 'bigquery')
                read = f'bigquery.Client().query({sql.select_all(op)!r}).to_dataframe()'
            case _:  # pragma: no cover
                raise AssertionError(f'semantic analysis rejects source {op.format!r}')
        self.lines.append(f'{name} = {read}')

    def _source_value(self, value: ir.SourceArg) -> str:
        if isinstance(value, ir.EnvVar):
            self.modules.add('os')
            return f'os.environ[{value.name!r}]'
        return repr(value)

    def _filter(self, op: ir.Filter) -> None:
        source = self.variables[op.input]
        name = self._bind(op)
        self.lines.append(f'{name} = {source}[{self._expr(op.condition, source)}]')

    def _select(self, op: ir.Select) -> None:
        source = self.variables[op.input]
        name = self._bind(op)
        self.lines.append(f'{name} = {source}[{list(op.columns)!r}]')

    def _train(self, op: ir.Train) -> None:
        data = self.variables[op.input]
        model = self._bind(op)
        module, classifier, regressor, seeded = ESTIMATORS[op.algorithm]
        estimator = classifier if op.task == 'classification' else regressor
        assert estimator is not None, 'semantic analysis rejects unsupported tasks'
        self._import(module, estimator)
        self._import('sklearn.model_selection', 'train_test_split')

        kwargs = [f'{PARAM_NAMES.get(key, key)}={value!r}' for key, value in op.params]
        if seeded:
            kwargs.append(f'random_state={op.seed}')
        if op.features is None:
            features = f'{data}.drop(columns=[{op.target!r}])'
        else:
            features = f'{data}[{list(op.features)!r}]'
        stratify = 'None'
        if op.task == 'classification':
            stratify = f'{model}_y if {model}_y.value_counts().min() >= 2 else None'

        self._section(f'Train {op.name}: {op.algorithm} ({op.task})')
        self.lines += [
            f'{model}_X = pd.get_dummies({features})',
            f'{model}_y = {data}[{op.target!r}]',
            f'{model}_X_train, {model}_X_test, {model}_y_train, {model}_y_test = train_test_split(',
            f'    {model}_X,',
            f'    {model}_y,',
            f'    test_size={op.validation},',
            f'    random_state={op.seed},',
            f'    stratify={stratify},',
            ')',
            f'{model} = {estimator}({", ".join(kwargs)})',
            f'{model}.fit({model}_X_train, {model}_y_train)',
            (
                f"print(f'{op.name}: {op.algorithm} {op.task},"
                f" trained on {{len({model}_X_train)}} rows, validated on {{len({model}_X_test)}}')"
            ),
        ]

    def _evaluate(self, op: ir.Evaluate) -> None:
        model = self.variables[op.model]
        self._section(f'Evaluate {op.name}')
        self.lines.append(f'{model}_pred = {model}.predict({model}_X_test)')
        if any(METRIC_FUNCTIONS[metric][1] for metric in op.metrics):
            self.lines.append(
                f"{model}_average = 'binary' if set({model}_y.unique()) <= {{0, 1}} else 'weighted'"
            )
        if 'auc' in op.metrics:
            self.lines += [
                f'{model}_proba = {model}.predict_proba({model}_X_test)',
                (
                    f'{model}_scores = {model}_proba[:, 1] if {model}_proba.shape[1] == 2'
                    f' else {model}_proba'
                ),
            ]
        width = max(len(metric) for metric in op.metrics)
        for metric in op.metrics:
            function, averaged = METRIC_FUNCTIONS[metric]
            self._import('sklearn.metrics', function)
            args = [f'{model}_y_test', f'{model}_pred']
            if metric == 'auc':
                args = [f'{model}_y_test', f'{model}_scores', "multi_class='ovr'"]
            elif averaged:
                args += [f'average={model}_average', 'zero_division=0']
            self.lines.append(
                f"print(f'  {metric:<{width}}  {{{function}({', '.join(args)}):.4f}}')"
            )

    def _expr(self, expr: ast.Expr, frame: str) -> str:
        match expr:
            case ast.Name(value=column):
                return f'{frame}[{column!r}]'
            case ast.IntLiteral(value=number) | ast.FloatLiteral(value=number):
                return repr(number)
            case ast.StringLiteral(value=text):
                return repr(text)
            case ast.BoolLiteral(value=flag):
                return repr(flag)
            case ast.Unary(op='not', operand=operand):
                return f'~({self._expr(operand, frame)})'
            case ast.Unary(op=op, operand=operand):
                return f'{op}({self._expr(operand, frame)})'
            case ast.Binary(op=op, left=left, right=right):
                python_op = BINARY_OPERATORS.get(op, op)
                return f'({self._expr(left, frame)} {python_op} {self._expr(right, frame)})'
        raise AssertionError(f'semantic analysis rejects {expr!r} in filters')  # pragma: no cover

    def _assign_names(self) -> None:
        """Pick a Python variable per Eigrel name that clashes with nothing else in the script."""
        models = {op.name for op in self.graph.ops if isinstance(op, ir.Train)}
        taken: set[str] = set()
        for op in self.graph.ops:
            if op.name in self.names:
                continue
            helpers = MODEL_HELPERS if op.name in models else ()
            variable = op.name
            while (
                keyword.iskeyword(variable)
                or variable in RESERVED
                or variable in taken
                or any(variable + suffix in taken for suffix in helpers)
            ):
                variable += '_'
            taken.add(variable)
            taken.update(variable + suffix for suffix in helpers)
            self.names[op.name] = variable

    def _bind(self, op: ir.Op) -> str:
        self.variables[op.id] = self.names[op.name]
        return self.variables[op.id]

    def _import(self, module: str, name: str) -> None:
        self.imports.setdefault(module, set()).add(name)

    def _section(self, title: str) -> None:
        self.lines += ['', f'# {title}']


def generate(graph: ir.Graph, source_name: str = '<eigrel>') -> str:
    """Generate a standalone Python script from an IR graph."""
    return _Generator(graph).generate(source_name)
