"""SQL backend: turn the data part of the IR into one SELECT per dataset.

Each dataset is compiled for the engine its source lives in: the database of a `sql()` source,
BigQuery for `bigquery()`, and DuckDB for files, which can query CSV, Parquet and JSON directly.
Models are not part of the SQL output.
"""

from dataclasses import dataclass

from eigrel import __version__
from eigrel.compiler import ast, ir

FILE_READERS = {'csv': 'read_csv_auto', 'parquet': 'read_parquet', 'json': 'read_json_auto'}
OPERATORS = {'and': 'AND', 'or': 'OR', '==': '=', '!=': '<>'}


@dataclass(frozen=True)
class Dialect:
    name: str
    quote: str
    # BigQuery has no % operator, only MOD().
    mod_function: bool = False


ANSI = Dialect('ansi', '"')
DUCKDB = Dialect('duckdb', '"')
BIGQUERY = Dialect('bigquery', '`', mod_function=True)
MYSQL = Dialect('mysql', '`')
# Database URL scheme (before any +driver) -> dialect; anything else uses ANSI quoting.
URL_DIALECTS = {
    'mysql': MYSQL,
    'mariadb': MYSQL,
    'postgresql': Dialect('postgresql', '"'),
    'postgres': Dialect('postgresql', '"'),
    'sqlite': Dialect('sqlite', '"'),
}


@dataclass(frozen=True)
class Query:
    dataset: str
    source: ir.Load
    columns: tuple[str, ...] | None
    filters: tuple[ast.Expr, ...]


def dialect_for(load: ir.Load) -> Dialect:
    if load.format in FILE_READERS:
        return DUCKDB
    if load.format == 'bigquery':
        return BIGQUERY
    url = load.args[0]
    if isinstance(url, ir.EnvVar):
        return ANSI
    scheme = url.split(':', 1)[0].split('+', 1)[0].lower()
    return URL_DIALECTS.get(scheme, ANSI)


def dataset_queries(graph: ir.Graph) -> list[Query]:
    """The final state of every dataset as a source plus its filters and projection."""
    latest: dict[str, int] = {}
    for op in graph.ops:
        if isinstance(op, ir.Load | ir.Filter | ir.Select):
            latest[op.name] = op.id
    return [_query(graph, name, op_id) for name, op_id in latest.items()]


def _query(graph: ir.Graph, name: str, op_id: int) -> Query:
    filters: list[ast.Expr] = []
    columns: tuple[str, ...] | None = None
    op = graph.ops[op_id]
    while not isinstance(op, ir.Load):
        match op:
            case ir.Filter():
                filters.append(op.condition)
                op = graph.ops[op.input]
            case ir.Select():
                # Walking backwards, the first select seen is the last one applied.
                columns = op.columns if columns is None else columns
                op = graph.ops[op.input]
            case _:  # pragma: no cover
                raise AssertionError(f'unexpected op {op!r} in a dataset chain')
    # Semantic analysis guarantees every filter only uses columns that exist where it runs, so
    # filters and the projection can be merged into a single SELECT.
    return Query(name, op, columns, tuple(reversed(filters)))


def render(query: Query) -> str:
    dialect = dialect_for(query.source)
    columns = '*'
    if query.columns is not None:
        columns = ', '.join(_identifier(column, dialect) for column in query.columns)
    sql = f'SELECT {columns} FROM {_from(query.source, dialect)}'
    if query.filters:
        sql += ' WHERE ' + ' AND '.join(_expr(f, dialect) for f in query.filters)
    return sql


def select_all(load: ir.Load) -> str:
    """SELECT * from a single source, as used by the Python backend to read databases."""
    return render(Query(load.name, load, None, ()))


def generate(graph: ir.Graph, source_name: str = '<eigrel>') -> str:
    """Generate SQL for every dataset in the program."""
    blocks = [f'-- Generated by eigrel {__version__} from {source_name}. Do not edit.']
    for query in dataset_queries(graph):
        dialect = dialect_for(query.source)
        blocks.append(
            f'-- dataset {query.dataset} ({query.source.format}, {dialect.name} dialect)\n'
            f'{render(query)};'
        )
    models = sorted({op.name for op in graph.ops if isinstance(op, ir.Train)})
    if models:
        blocks.append(f'-- Models are not compiled to SQL: {", ".join(models)}')
    return '\n\n'.join(blocks) + '\n'


def _from(load: ir.Load, dialect: Dialect) -> str:
    if load.format in FILE_READERS:
        return f'{FILE_READERS[load.format]}({_string(str(load.args[0]))})'
    if load.format == 'bigquery':
        return f'`{load.args[0]}`'
    table = str(load.args[1])
    return '.'.join(_identifier(part, dialect) for part in table.split('.'))


def _identifier(name: str, dialect: Dialect) -> str:
    return dialect.quote + name.replace(dialect.quote, dialect.quote * 2) + dialect.quote


def _string(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def _expr(expr: ast.Expr, dialect: Dialect) -> str:
    match expr:
        case ast.Name(value=column):
            return _identifier(column, dialect)
        case ast.IntLiteral(value=number) | ast.FloatLiteral(value=number):
            return repr(number)
        case ast.StringLiteral(value=text):
            return _string(text)
        case ast.BoolLiteral(value=flag):
            return 'TRUE' if flag else 'FALSE'
        case ast.Unary(op='not', operand=operand):
            return f'(NOT {_expr(operand, dialect)})'
        case ast.Unary(op=op, operand=operand):
            return f'({op}{_expr(operand, dialect)})'
        case ast.Binary(op='%', left=left, right=right) if dialect.mod_function:
            return f'MOD({_expr(left, dialect)}, {_expr(right, dialect)})'
        case ast.Binary(op=op, left=left, right=right):
            sql_op = OPERATORS.get(op, op)
            return f'({_expr(left, dialect)} {sql_op} {_expr(right, dialect)})'
    raise AssertionError(f'semantic analysis rejects {expr!r} in filters')  # pragma: no cover
